# Site settings
title: Data Analyst 
subtitle: Portfolio
email: mariamaske2063@gmail.com
description: Data Analyst Portfolio
baseurl: ""
url: "https://mariamaske.github.io"
author:
street_address:
city: Berlin
state: Berlin
zip_code:
country: Germany
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://gitlab.com/u/andrewbanchich
gitlab_url: 
googleplus_url:
instagram_url:
tableau_url: https://public.tableau.com/app/profile/maria.maske7402/vizzes
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
