# Site settings
title: Data Analyst 
subtitle: Portfolio
email: mariamaske2063@gmail.com
description: Data Analyst Portfolio
baseurl: ""
url: "https://mariamaske.github.io"
author:
street_address:
city: Berlin
state: Berlin
zip_code:
country: Germany
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/mariamaske
gitlab_url: 
googleplus_url:
instagram_url:
tableau_url: https://public.tableau.com/app/profile/maria.maske7402/vizzes
linkedin_url: https://www.linkedin.com/in/maria-maske-a04b0618a/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
